settings:
  root_dir: "./datasets/celeba/images"
  img_binary_folder: "/home/ubuntu/GAN-based-Face-Unmasking/1_dataprepare/img_binary/"
  img_masked_folder: "/home/ubuntu/GAN-based-Face-Unmasking/2_detector/img_masked/"
  # train_anns: "./datasets/celeba/annotations/train.csv"
  # val_anns: "./datasets/celeba/annotations/val.csv"

  checkpoint_path: 'weights' 
  #sample_folder: 'sample' 

  cuda: True
  lr: 0.001
  batch_size: 4
  num_workers: 4

  step_iters: [50000, 75000, 100000]
  gamma: 0.1
  
  visualize_per_iter: 1000
  save_per_iter: 1000
  print_per_iter: 10
  num_epochs: 100

  img_size: 128

